#include "../Keyboard.h"

#include <Windows.h>

namespace PGM::Platform::Input
{

namespace detail
{
    static constexpr int convertToPlatformKey(Key key)
    {
        switch (key)
        {
        case A:
            return 'A';
        case B:
            return 'B';
        case C:
            return 'C';
        case D:
            return 'D';
        case E:
            return 'E';
        case F:
            return 'F';
        case G:
            return 'G';
        case H:
            return 'H';
        case I:
            return 'I';
        case J:
            return 'J';
        case K:
            return 'K';
        case L:
            return 'L';
        case M:
            return 'M';
        case N:
            return 'N';
        case O:
            return 'O';
        case P:
            return 'P';
        case Q:
            return 'Q';
        case R:
            return 'R';
        case S:
            return 'S';
        case T:
            return 'T';
        case U:
            return 'U';
        case V:
            return 'V';
        case W:
            return 'W';
        case X:
            return 'X';
        case Y:
            return 'Y';
        case Z:
            return 'Z';
        case Num0:
            return '0';
        case Num1:
            return '1';
        case Num2:
            return '2';
        case Num3:
            return '3';
        case Num4:
            return '4';
        case Num5:
            return '5';
        case Num6:
            return '6';
        case Num7:
            return '7';
        case Num8:
            return '8';
        case Num9:
            return '9';
        case Escape:
            return VK_ESCAPE;
        case LControl:
            return VK_LCONTROL;
        case LShift:
            return VK_LSHIFT;
        case LAlt:
            return VK_LMENU;
        case LSystem:
            return VK_LWIN;
        case RControl:
            return VK_RCONTROL;
        case RShift:
            return VK_RSHIFT;
        case RAlt:
            return VK_RMENU;
        case RSystem:
            return VK_RWIN;
        case Menu:
            return VK_APPS;
        case LBracket:
            return VK_OEM_4;
        case RBracket:
            return VK_OEM_6;
        case Semicolon:
            return VK_OEM_1;
        case Comma:
            return VK_OEM_COMMA;
        case Period:
            return VK_OEM_PERIOD;
        case Apostrophe:
            return VK_OEM_7;
        case Slash:
            return VK_OEM_2;
        case Backslash:
            return VK_OEM_5;
        case Grave:
            return VK_OEM_3;
        case Equal:
            return VK_OEM_PLUS;
        case Hyphen:
            return VK_OEM_MINUS;
        case Space:
            return VK_SPACE;
        case Enter:
            return VK_RETURN;
        case Backspace:
            return VK_BACK;
        case Tab:
            return VK_TAB;
        case PageUp:
            return VK_PRIOR;
        case PageDown:
            return VK_NEXT;
        case End:
            return VK_END;
        case Home:
            return VK_HOME;
        case Insert:
            return VK_INSERT;
        case Delete:
            return VK_DELETE;
        case Add:
            return VK_ADD;
        case Subtract:
            return VK_SUBTRACT;
        case Multiply:
            return VK_MULTIPLY;
        case Divide:
            return VK_DIVIDE;
        case Left:
            return VK_LEFT;
        case Right:
            return VK_RIGHT;
        case Up:
            return VK_UP;
        case Down:
            return VK_DOWN;
        case Numpad0:
            return VK_NUMPAD0;
        case Numpad1:
            return VK_NUMPAD1;
        case Numpad2:
            return VK_NUMPAD2;
        case Numpad3:
            return VK_NUMPAD3;
        case Numpad4:
            return VK_NUMPAD4;
        case Numpad5:
            return VK_NUMPAD5;
        case Numpad6:
            return VK_NUMPAD6;
        case Numpad7:
            return VK_NUMPAD7;
        case Numpad8:
            return VK_NUMPAD8;
        case Numpad9:
            return VK_NUMPAD9;
        case F1:
            return VK_F1;
        case F2:
            return VK_F2;
        case F3:
            return VK_F3;
        case F4:
            return VK_F4;
        case F5:
            return VK_F5;
        case F6:
            return VK_F6;
        case F7:
            return VK_F7;
        case F8:
            return VK_F8;
        case F9:
            return VK_F9;
        case F10:
            return VK_F10;
        case F11:
            return VK_F11;
        case F12:
            return VK_F12;
        case F13:
            return VK_F13;
        case F14:
            return VK_F14;
        case F15:
            return VK_F15;
        case Pause:
            return VK_PAUSE;
        default:
            return 0;
        }
    }

} // namespace detail

bool isKeyDown(Key key)
{
    const auto win32Key = detail::convertToPlatformKey(key);
    return (GetAsyncKeyState(win32Key) & 0x8000) != 0;
}

} // namespace PGM::Platform::Input